app = 'your-serverless-postgres'
primary_region = 'iad'

[build]
  dockerfile = 'oriole/Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 5432
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  [[services.ports]]
    handlers = ['pg_tls']
    port = 5432
  [[services.tcp_checks]]
    grace_period = '10s'
    interval = '15s'
    timeout = '2s'

[mounts]
source = 'data'
destination = '/var/lib/postgresql/'
initial_size = '1gb'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
